### ISSUE TITLE
How can the fieldImage data be used?

### ISSUE THREAD

**Issue by Naren219** [PWNAGERobotics/ScoutingPASS#31]

**Comment by fuddster** [comment]
For the Auto Start, it's just a matter of seeing if their robot lines up in the same spot as your team.  

The Shooting Spot data can be used to see where a robot tends to shoot from.   You can create a heatmap to show it visually.   Then you'll know where to defend them in upcoming matches.

If that answers your questions, feel free to close the issue.

P.S. Questions are better posed in the Discussions tab.  That way everyone can participate in the discussion.
