### ISSUE TITLE
Only 1st occurrence of ';' is removed from comment

### ISSUE THREAD

**Issue by vosdeveloper** [PWNAGERobotics/ScoutingPASS#4]
In scoutingPASS.js, there is the following line of code that removes any user entered semicolons so it does not interfere with the parsing of the data after reading the QR code.

str=str+code+'='+e.value.replace(";", "-")

However, it only removes the 1st occurrence.  Perhaps replace the above line of code with the following line:

str=str+code+'='+e.value.split(';').join('-')

**Comment by fuddster** [comment]
Thanks for the fix.   We will incorporate this shortly.
