### ISSUE TITLE
Multiple field_image elements on one page causes formatting issues

### ISSUE THREAD

**Issue by billyParmenter** [PWNAGERobotics/ScoutingPASS#40]
When multiple fields are added to one page the formatting is not as expected.

The following config:
![image](https://user-images.githubusercontent.com/45088153/162074436-b76e4624-efc5-4608-b93d-fa6dbb8eb0d3.png)

will output the following page:
![image](https://user-images.githubusercontent.com/45088153/162074673-76057a17-dd37-4fa5-b2bc-ea64b6b159dd.png)

When a second field_image is added as shown below:
![image](https://user-images.githubusercontent.com/45088153/162074815-7ba5382a-b4c9-4a2d-bb82-641d9c63c21b.png)

Will output the following page:
![image](https://user-images.githubusercontent.com/45088153/162074925-e5b1c025-6407-4426-8c6e-40c723234fe3.png)

**Comment by fuddster** [comment]
Thank you for pointing that out.  We'll check it out and see what's going on.

**Comment by fuddster** [comment]
This has been fixed for the 2023 season.
