### ISSUE TITLE
Clear button  for timer

### ISSUE THREAD

**Issue by lidor51** [PWNAGERobotics/ScoutingPASS#53]
After playing with your demo, a clear/cancel button to timer could be helpful (e.g., in case the robot dropped its game piece and went to do something else).

**Comment by fuddster** [comment]
I think I understand what you are saying. 

You can do that now, by clicking the stop button and then hitting reset.  (The start button becomes a stop button after it's clicked)  It will stop the timer and reset it to zero.   A single button would be cleaner, but also more cluttered in the interface.

Should the reset button stop the timer as well?

**Comment by lidor51** [comment]
From your demo, stop only stops, without doing a reset.

> Should the reset button stop the timer as well?
I can see both scenarios, probably the more common one is reset + stop.

**Comment by fuddster** [comment]
Ok.  Still not sure if you're talking about the cycle timer (on the Teleop screen) or the plain timer (on Endgame screen).

However, either way, I think you've pointed out some good improvements:

Cycle Timer needs a "reset button" to stop the timer and reset it to zero.  As you mentioned in your first message, if they drop a piece and go do something else, there is a need to stop and reset the timer.

For the plain Timer, the reset button should stop the timer in addition to zeroing it out.

If I'm still misunderstanding you, please don't hesitate to correct me.

We'll get these changes in soon.   

Thanks for the suggestions!

**Comment by fuddster** [comment]
The "Reset" button now stops the timer and sets the timer to zero.
Added a Reset and Undo button to the Cycle timer.
