### ISSUE TITLE
Cycle outputs 0 instead of array

### ISSUE THREAD

**Issue by jckwik** [PWNAGERobotics/ScoutingPASS#54]
Using the default 2023 config and entering ["5.6","10.1","17.9","19.1","2.5","0"] into the cycle times (just clicked the button a bunch for fun) the following was the QR output: 

s=JK;e=2023ilch;l=qm;m=1;r=r1;t=;as=[26];am=1;auh=1;aum=0;aul=0;aoh=1;aom=0;aol=0;ad=e;tct=0;tuh=2;tum=0;tul=0;toh=0;tom=1;tol=0;tfc=0;wd=0;lnk=1;cif=g;dt=0;fs=e;cn=1;ds=x;ls=0;dr=x;sd=1;sr=3;d=0;coo=0;all=0;co=;cnf=a

tct=0 should probably include some/all of the values from the cycle times - I'm unsure of the format that I was expecting but I was expecting something.

**Comment by jckwik** [comment]
Looked into it a little bit more: 

Not sure how it's updating the visible element on the page but not updating the 'value' attribute, but that appears to be the problem: 
![image](https://user-images.githubusercontent.com/8590587/211433777-d9385bde-2cec-446e-9029-88ee65a1050a.png)

**Comment by jckwik** [comment]
Additionally getData() is querying for all of the inputs that have 'input' in them, which cycletime_tct does not. Unless I'm misreading how getData() works, in which case ignore me.

**Comment by fuddster** [comment]
Joshua, you found our newest (untested) feature.

The team was talking yesterday and remarking on how valuable a cycle timer would be.   So, I was in the middle of coding it and accidentally committed some of the code to the main branch.   It wasn't ready for use yet.

It's almost ready.   Just doing a little more testing on it and then I'll release it to the main branch.   Look for it by Wednesday at the latest.  Hopefully much sooner!

I'll comment here when it goes live.

**Comment by fuddster** [comment]
Please try the cycle timer now and let me know how it works for you.

**Comment by jckwik** [comment]
Aha! Oops, I know that pain all too well. Looks to be good now, thank you!

I'm also looking at testing the sheets integration as that is the exact feature we are looking for - for our first event there's going to be some students scouting remotely as not everyone is able to make the trip from Rochester NY to Miami FL, so having a solution that automatically syncs our data together is a huge positive if it works. 

In the meantime I wanted to thank you for this wonderful tool - we're looking at using it for data collection this season if we can figure out some of the details. This is certainly more reliable than a google form.
