### ISSUE TITLE
Attempting to Set Up Google Sheet Support causes Domain (CORS) Error

### ISSUE THREAD

**Issue by KrishWu** [PWNAGERobotics/ScoutingPASS#64]
While trying to set up the google sheet support and following the instructions I attempted to make the new deployment and ran into this issue.
![image](https://user-images.githubusercontent.com/66881117/213890334-43e74adb-e6ab-4763-9bde-c473bb29c4bc.png)
I don't know if this has been seen before by anyone else. This may be a bug and explain why it worked for the creator of this project as they have an account from the same domain or such. Just some ideas. Not one hundred percent sure, but thought I would point it out in this issue to see if anyone has run into this issue.

**Comment by KrishWu** [comment]
This issue was created by me trying to set up the script through my google account on a google sheet owned by another account. I just thought I would add this if anyone else is facing this problem in the future.

**Comment by fuddster** [comment]
Thanks for sharing.
