### ISSUE TITLE
Black text with input boxes with black backgrounds makes it impossible to read 

### ISSUE THREAD

**Issue by JediScoy** [PWNAGERobotics/ScoutingPASS#86]
On a PC the input boxes had white backgrounds regardless of page background color. On an android tablet the black background pages would also have black input boxes (maybe they are transparent?). Changing tablet color themes, desktop mode, etc still left it black on black. CSS fix worked for us.  I fixed on our fork with this:

line 222-ish
input {
    font-size: 16px;
    font: roboto;
    color: black;
    background-color: white;
}

**Comment by fuddster** [comment]
Thanks for the fix!   

We're a little busy now in the middle of competition season, but we'll test your fix on our repository after the season ends and incorporate your changes.

Thank you.

**Comment by fuddster** [comment]
Thanks for the fix @JediScoy!    The fix has been applied and is live now.
