### ISSUE TITLE
Fix display data when using tsv (tab separated values)

### ISSUE THREAD

**Issue by fuddster** [PWNAGERobotics/ScoutingPASS#99]
When clicking the Display Data button on the QR screen the message "unsupported dataFormat" is displayed.

Fix the feature to correctly display the data in tsv format

**Comment by usermane6** [comment]
Hey, I'm on team 1391, and we were thinking of using this as our scouting code. I was looking through the code, trying to get this working my end, and the issue seemed to be that in the crescendo_config.js file, the dataFormat is selected as "tvs", and not "tsv". Changing this value seemed to fix it for me.

**Comment by fuddster** [comment]
> the dataFormat is selected as "tvs", and not "tsv"

Good catch Tim!  (@usermane6 )  That was exactly the problem.

Good luck to the Metal Moose this year!    Let me know if you need anything.  Happy to help teams using ScoutingPASS!

**Comment by fuddster** [comment]
Fix applied
